version: '3'

services:
  llm-app:
    build:
      context: ./llm-app
    ports:
      - "5001:5000"
    volumes:
      - ./llm-app:/app
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped
